version: '3.9'
services:
  react:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules

  api:
    build: ./api
    ports:
      - "4000:4000"
    command:
      sh -c "nodemon --legacy-watch index"
      